# Use case configuration for Qualcomm Shikra IQS EVK.
# Codec: MAX98091 speaker, VA DMIC capture
# Speaker: hw:0,2   DMIC: hw:0,2

SectionVerb {
	EnableSequence [
		cset "name='PRIMARY_MI2S_RX Audio Mixer MultiMedia1' 1"
		cset "name='MultiMedia3 Mixer VA_CODEC_DMA_TX_0' 1"
	]
	Include.e.File "/codecs/max98090/EnableSeq.conf"
	Value {
		TQ "HiFi"
	}
}

SectionDevice."Earpiece" {
	Comment "Earpiece playback"

	Value {
		PlaybackPCM "hw:${CardId},0"
		PlaybackMixer "default:${CardId}"
	}

	EnableSequence [
		cset "name='Speaker Left Switch' on"
		cset "name='Speaker Right Switch' on"
		cset "name='Speaker Switch' on"
	]

	DisableSequence [
		cset "name='Speaker Left Switch' off"
		cset "name='Speaker Right Switch' off"
		cset "name='Speaker Switch' off"
	]

}

SectionDevice."Mic" {
	Comment "Internal Digital Microphone capture"

	Include.vadm0e.File "/codecs/qcom-lpass/va-macro/DMIC0EnableSeq.conf"
	Include.vadm0d.File "/codecs/qcom-lpass/va-macro/DMIC0DisableSeq.conf"
	Include.vadm1e.File "/codecs/qcom-lpass/va-macro/DMIC1EnableSeq.conf"
	Include.vadm1d.File "/codecs/qcom-lpass/va-macro/DMIC1DisableSeq.conf"

	Value {
		CapturePriority 100
		CapturePCM "hw:${CardId},2"
		CaptureChannels 1
	}
}
