# RT1015 specific volume control settings

BootSequence [
	cset "name='Left Bypass Boost' on"
	cset "name='Right Bypass Boost' on"
	cset "name='Left Mono LR Select' Left"
	cset "name='Right Mono LR Select' Right"
	cset "name='Left Boost Mode' on"
	cset "name='Left Boost Mode' on"
	cset "name='Left DAC Playback Volume' 124"
	cset "name='Right DAC Playback Volume' 124"
]
