# cs47l47 specific control settings

LibraryConfig.remap.Config {
	ctl.default.map {
		"name='cs47l47 Jack Microphone Capture Switch'" {
			"name='cs47l47 FU 36 Channel Switch'".vindex.0 0
			"name='cs47l47 FU 36 Channel Switch'".vindex.1 1
		}
		"name='cs47l47 Jack Microphone Capture Volume'" {
			"name='cs47l47 FU 36 Channel Volume'".vindex.0 0
			"name='cs47l47 FU 36 Channel Volume'".vindex.1 1
		}
	}
	ctl.default.map {
		"name='cs47l47 Headphone Playback Switch'" {
			"name='cs47l47 FU 41 Channel Switch'".vindex.0 0
			"name='cs47l47 FU 41 Channel Switch'".vindex.1 1
		}
		"name='cs47l47 Headphone Playback Volume'" {
			"name='cs47l47 FU 41 Channel Volume'".vindex.0 0
			"name='cs47l47 FU 41 Channel Volume'".vindex.1 1
		}
	}
}
