Syntax 6

SectionVerb {
	Value {
		TQ "HiFi"
	}
}

# The three HDMI devices below all drive the same raw PCM (hw:${CardId},0)
# with a different channel count, and are marked as mutually exclusive via
# ConflictingDevices.

SectionDevice."HDMI Stereo" {
	Comment "HDMI/DP Stereo"

	ConflictingDevices [
		"HDMI Surround 51"
		"HDMI Surround 71"
	]

	Value {
		PlaybackPCM "hw:${CardId},0"
		PlaybackChannels "2"
		PlaybackPriority "300"
	}
}

SectionDevice."HDMI Surround 51" {
	Comment "HDMI/DP Surround 5.1"

	ConflictingDevices [
		"HDMI Stereo"
		"HDMI Surround 71"
	]

	Value {
		PlaybackPCM "hw:${CardId},0"
		PlaybackChannels "6"
		PlaybackPriority "200"
	}
}

SectionDevice."HDMI Surround 71" {
	Comment "HDMI/DP Surround 7.1"

	ConflictingDevices [
		"HDMI Stereo"
		"HDMI Surround 51"
	]

	Value {
		PlaybackPCM "hw:${CardId},0"
		PlaybackChannels "8"
		PlaybackPriority "100"
	}
}
