# Use case configuration for Microsoft Blackrock.
# Author: Jens Glathe <jens.glathe@oldschoolsolutions.biz>
# Original Author: Srinivas Kandagatla <srinivas.kandagatla@linaro.org>

SectionVerb {
	EnableSequence [
		cset "name='DISPLAY_PORT_RX_0 Audio Mixer MultiMedia1' 1"
		cset "name='DISPLAY_PORT_RX_1 Audio Mixer MultiMedia2' 1"
		cset "name='DISPLAY_PORT_RX_2 Audio Mixer MultiMedia3' 1"
	]

	Value {
		TQ "HiFi"
	}
}

SectionDevice."HDMI0" {
	Comment "USB/DisplayPort 0 playback"

	ConflictingDevice [
		"HDMI1"
		"HDMI2"
	]

	EnableSequence [
		cset "name='DISPLAY_PORT_RX_0 Audio Mixer MultiMedia1' 1"
		cset "name='DISPLAY_PORT_RX_1 Audio Mixer MultiMedia2' 0"
		cset "name='DISPLAY_PORT_RX_2 Audio Mixer MultiMedia3' 0"
	]

	DisableSequence [
		cset "name='DISPLAY_PORT_RX_0 Audio Mixer MultiMedia1' 0"
	]

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId},0"
		PlaybackChannels 2
		JackControl "DP0 Jack"
	}
}

SectionDevice."HDMI1" {
	Comment "USB/DisplayPort 1 playback"

	ConflictingDevice [
		"HDMI0"
		"HDMI2"
	]

	EnableSequence [
		cset "name='DISPLAY_PORT_RX_0 Audio Mixer MultiMedia1' 0"
		cset "name='DISPLAY_PORT_RX_1 Audio Mixer MultiMedia2' 1"
		cset "name='DISPLAY_PORT_RX_2 Audio Mixer MultiMedia3' 0"
	]

	DisableSequence [
		cset "name='DISPLAY_PORT_RX_1 Audio Mixer MultiMedia2' 0"
	]

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId},1"
		PlaybackChannels 2
		JackControl "DP1 Jack"
	}
}

SectionDevice."HDMI2" {
	Comment "miniDP playback"

	ConflictingDevice [
		"HDMI0"
		"HDMI1"
	]

	EnableSequence [
		cset "name='DISPLAY_PORT_RX_0 Audio Mixer MultiMedia1' 0"
		cset "name='DISPLAY_PORT_RX_1 Audio Mixer MultiMedia2' 0"
		cset "name='DISPLAY_PORT_RX_2 Audio Mixer MultiMedia3' 1"
	]

	DisableSequence [
		cset "name='DISPLAY_PORT_RX_2 Audio Mixer MultiMedia3' 0"
	]

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId},2"
		PlaybackChannels 2
		JackControl "DP2 Jack"
	}
}
