Syntax 4

SectionUseCase."HiFi" {
	File "/Qualcomm/sc8280xp/Blackrock-HiFi.conf"
	Comment "HiFi quality Music."
}

Include.card-init.File "/lib/card-init.conf"
Include.ctl-remap.File "/lib/ctl-remap.conf"
