# RT712 specific volume control settings

BootSequence [
	cset "name='rt712 FU05 Playback Volume' 87"
	cset "name='rt712 ADC 23 Mux' 'MIC2'"
	cset "name='rt712 FU0F Capture Volume' 57"
	cset "name='rt712 FU0F Capture Switch' 1"
]

If.rt712dmic_init {
	Condition {
		Type String
		String1 "rt712-dmic"
		String2 "${var:MicCodec1}"
	}
	True.BootSequence [
		cset "name='rt712-dmic ADC 25 Mux' 'DMIC1'"
		cset "name='rt712-dmic FU1E Capture Switch' 1"
	]
}

If.rt712vb_init {
	Condition {
		Type RegexMatch
		# guard with '=' to avoid empty or rt712-dmic string matching
		Regex "=(rt712(-sdca)?)="
		String "=${var:MicCodec1}="
	}
	True.BootSequence [
		# RT712-VB integrated with DMIC
		cset "name='rt712 FU1E Capture Switch' 1"
		cset "name='rt712 FU1E Capture Volume' 47"
		cset "name='rt712 ADC 0A Mux' 'DMIC1'"
		cset "name='rt712 ADC 0B Mux' 'DMIC2'"
	]
}
