SectionDevice."Mic" {
	Comment "Digital Microphone"

	Value {
		CapturePCM "hw:${CardId},2"
		CaptureChannels 4
		# While NHLT only has entry for 4 channel DMIC, only 2 channels
		# record anything reasonable, so for Front End to work properly
		# remap two working channels onto 2 broken ones.
		CaptureChannel0 0
		CaptureChannel1 1
		CaptureChannel2 0
		CaptureChannel3 1
		CaptureMixerElem "DMIC"
	}
}
