# RT1320 amp specific switch control settings

DefineMacro.rt1320spkled.If.0 {
	Condition {
		Type RegexMatch
		Regex "${var:__ForAmps}"
		String "${var:SpeakerAmps}"
	}
	True.Macro [
		{ SetLED { LED="speaker" Action="attach" CtlId="rt1320-${var:__Amp} OT23 L Switch" } }
		{ SetLED { LED="speaker" Action="attach" CtlId="rt1320-${var:__Amp} OT23 R Switch" } }
	]
}

If.spk_init_rt1320 {
	Condition {
		Type String
		Needle "rt1320"
		Haystack "${var:MultiSpeakerShadow}"
	}
	True {
		Macro.num1.rt1320spkled { ForAmps "[12]" Amp 1 }
		Macro.num2.rt1320spkled { ForAmps "2" Amp 2 }
	}
}

Define.SpeakerMixerElem "rt1320-1 OT23"

If.oneAmp {
	Condition {
		Type RegexMatch
		Regex "1"
		String "${var:SpeakerAmps}"
	}
	True {
		Define.SpeakerMixerElem "rt1320 OT23"
		LibraryConfig.remap.Config {
			ctl.default.map {
				"name='rt1320 OT23 Playback Switch'" {
					"name='rt1320-1 OT23 L Switch'".vindex.0 0
					"name='rt1320-1 OT23 R Switch'".vindex.1 0
				}
			}
		}
	}
}

If.twoAmps {
	Condition {
		Type RegexMatch
		Regex "2"
		String "${var:SpeakerAmps}"
	}
	True {
		Define.SpeakerMixerElem "rt1320 OT23"
		LibraryConfig.remap.Config {
			ctl.default.map {
				"name='rt1320 OT23 Playback Switch'" {
					"name='rt1320-1 OT23 L Switch'".vindex.0 0
					"name='rt1320-1 OT23 R Switch'".vindex.0 0
					"name='rt1320-2 OT23 L Switch'".vindex.1 0
					"name='rt1320-2 OT23 R Switch'".vindex.1 0
				}
			}
		}
	}
}

# RT1320 DMIC specific switch control settings

Define.MicMixerElem "rt1320-1 FU"

DefineMacro.rt1320micled.If.0 {
	Condition {
		Type RegexMatch
		Regex "${var:__ForMics}"
		String "${var:Mics}"
	}
	True.Macro [{ SetLED { LED="mic" Action="attach" CtlId="rt1320-${var:__Mic} FU Capture Switch" } }]
}

If.mic_init_rt1320 {
	Condition {
		Type String
		Needle "rt1320"
		Haystack "${var:MultiMicShadow}"
	}
	True {
		Macro.num1.rt1320micled { ForMics "[12]" Mic 1 }
		Macro.num2.rt1320micled { ForMics "2" Mic 2 }

		If.twoMics {
			Condition {
				Type RegexMatch
				Regex "2"
				String "${var:Mics}"
			}
			True {
				Define.MicMixerElem "rt1320 FU"
				LibraryConfig.remap.Config {
					ctl.default.map {
						"name='rt1320 FU Capture Switch'" {
							"name='rt1320-1 FU Capture Switch'".vindex.0 0
							"name='rt1320-1 FU Capture Switch'".vindex.1 1
							"name='rt1320-1 FU Capture Switch'".vindex.2 2
							"name='rt1320-1 FU Capture Switch'".vindex.3 3
							"name='rt1320-2 FU Capture Switch'".vindex.4 0
							"name='rt1320-2 FU Capture Switch'".vindex.5 1
							"name='rt1320-2 FU Capture Switch'".vindex.6 2
							"name='rt1320-2 FU Capture Switch'".vindex.7 3
						}
					}
				}
			}
		}
	}
}
