Syntax 3

SectionUseCase."HiFi" {
    Comment "Blue Snowball"
}

SectionDefaults [
    cset "name='Mic Capture Volume' 100%"
    cset "name='Mic Capture Switch' on"
]

SectionDevice."Mic" {
    Comment "Microphone"
    Value {
        CapturePriority 100
        CapturePCM "hw:${CardId},0"
        CaptureChannels "1"
        CaptureChannelMap "0:0"
    }
    EnableSequence [
        cdev "hw:${CardId}"
    ]
    DisableSequence [
        cdev "hw:${CardId}"
    ]
}
