# cs42l43-spk specific control settings

LibraryConfig.remap.Config {
	ctl.default.map {
		"name='cs42l43 Speaker Playback Switch'" {
			"name='cs42l43 Speaker Digital Switch'".vindex.0 0
			"name='cs42l43 Speaker Digital Switch'".vindex.1 1
		}
	}
}

Macro [
	{ SetLED { LED="speaker" Action="attach" CtlId="cs42l43 Speaker Digital Switch" } }
]