# Use case Configuration for sof-soundwire card

SectionDevice."Speaker" {
	Comment "Speaker"

	EnableSequence [
		cset "name='Speaker Switch' on"
	]

	DisableSequence [
		cset "name='Speaker Switch' off"
	]

	If.cs42l43_spk_routing {
		Condition {
			Type RegexMatch
			Regex "spk:cs42l43-spk"
			String "${CardComponents}"
		}
		True.EnableSequence [
			cset "name='cs42l43 Speaker L Input 1' 'DP6RX1'"
			cset "name='cs42l43 Speaker R Input 1' 'DP6RX2'"
		]
		True.DisableSequence [
			cset "name='cs42l43 Speaker L Input 1' 'None'"
			cset "name='cs42l43 Speaker R Input 1' 'None'"
		]
	}

	Value {
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId},2"
		PlaybackMixer "default:${CardId}"
		PlaybackMixerElem "cs35l56 Speaker"
	}
}
