# Use case Configuration for sof-soundwire card

SectionDevice."Mic" {
	Comment "Microphones"

	ConflictingDevice [
		"Headset"
	]

	Value {
		CapturePriority 100
		CapturePCM "hw:${CardId},4"
		CaptureMixer "default:${CardId}"
		CaptureMixerElem "cs47l47 Microphone"
	}
}
