# Use case Configuration for sof-soundwire card

SectionDevice."Headphones" {
	Comment "Headphones"

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId},0"
		PlaybackMixer "default:${CardId}"
		PlaybackMixerElem "cs47l47 Headphone"
		JackControl "cs47l47 OT 43 Headphone Jack"
	}
}

SectionDevice."Headset" {
	Comment "Jack Microphone"

	Value {
		CapturePriority 200
		CapturePCM "hw:${CardId},1"
		CaptureMixer "default:${CardId}"
		CaptureMixerElem "cs47l47 Jack Microphone"
		JackControl "cs47l47 IT 31 Microphone Jack"
	}
}
