# Use case Configuration for sof-soundwire card

SectionVerb {
	EnableSequence [
		disdevall ""
	]

	Value.TQ "HiFi"
}

If.spk {
	Condition {
		Type String
		Empty "${var:SpeakerCodecFile}"
	}
	False.Include.a.File "/sof-soundwire/${var:SpeakerCodecFile}.conf"
}

If.mic {
	Condition {
		Type String
		Empty "${var:MicCodecFile}"
	}
	False.If.dup {
		Condition {
			Type String
			String1 "${var:MicCodecFile}"
			String2 "${var:SpeakerCodecFile}"
		}
		False.Include.a.File "/sof-soundwire/${var:MicCodecFile}.conf"
	}
}

If.headset {
	Condition {
		Type String
		Empty "${var:HeadsetCodecFile}"
	}
	False.If.dup {
		Condition {
			Type String
			# guard with "=" to avoid empty string matching
			Needle "=${var:HeadsetCodecFile}="
			Haystack "=${var:SpeakerCodecFile}=${var:MicCodecFile}="
		}
		False.Include.a.File "/sof-soundwire/${var:HeadsetCodecFile}.conf"
	}
}

<sof-soundwire/Hdmi.conf>
