Comment "Steinberg UR44C USB-Audio"

SectionUseCase."HiFi" {
	Comment "Default"
	File "/USB-Audio/Steinberg/UR44C-HiFi.conf"
}

Include.dhw.File "/common/directm.conf"

Macro.0.DirectUseCase { Id="Direct" PlaybackChannels=6 CaptureChannels=8 }
