# cs47l47 specific control settings

LibraryConfig.remap.Config {
	ctl.default.map {
		"name='cs47l47 Microphone Capture Switch'" {
			"name='cs47l47 FU 113 Channel Switch'".vindex.0 0
			"name='cs47l47 FU 113 Channel Switch'".vindex.1 1
		}
		"name='cs47l47 Microphone Capture Volume'" {
			"name='cs47l47 FU 113 Channel Volume'".vindex.0 0
			"name='cs47l47 FU 113 Channel Volume'".vindex.1 1
		}
	}
}

BootSequence [
	cset "name='cs47l47 FU 113 Channel Switch' 0"
]

Macro [
	{ SetLED { LED="mic" Action="attach" CtlId="cs47l47 FU 113 Channel Switch"} }
]
