SectionDevice."Line1" {
	Comment "Chat"

	Value {
		PlaybackPCM "hw:${CardId},0"
	}
}

SectionDevice."Speaker" {
	Comment "System"

	Value {
		PlaybackPCM "hw:${CardId},1"
	}
}

SectionDevice."Mic" {
	Comment "Microphone"

	Value {
		CapturePCM "hw:${CardId},0"
	}
}

SectionDevice."Line2" {
	Comment "Main"

	Value {
		CapturePCM "hw:${CardId},1"
	}
}
