# The RODECaster Pro II has two USB ports, each with its own PID.
# USB1 has additionally the special capability to send multiple additonal tracks (multitrack mode).
# The multitrack functionallity can be configured for output and input individually.
# This soundcard also provides two devices on USB1. Device 0 is always the Mic/Chat Track. Device 1 is the
# optional multitrack device.
Comment = "RODECaster Pro II USB"

Comment "RODECaster Pro II USB"
If.usb1 {
	Condition {
		Type String
		Haystack "${CardComponents}"
		Needle "USB19f7:0037"
	}
	True {
		# Multitrack is disabled for Input and Output
		SectionUseCase."HiFi" {
			Comment "RODECaster Pro II"
			File "/USB-Audio/RODE/RODECaster-Pro-II-USB1-HiFi.conf"
		}
	}
}
If.usb1_multitrack {
	Condition {
		Type String
		Haystack "${CardComponents}"
		Needle "USB19f7:0072"
	}
	True {
		# Multitrack is enabled for Input and Output
		SectionUseCase."HiFi" {
			Comment "RODECaster Pro II"
			File "/USB-Audio/RODE/RODECaster-Pro-II-USB1-Multitrack-HiFi.conf"
		}
	}
}
If.usb1_multitrack_playback {
	Condition {
		Type String
		Haystack "${CardComponents}"
		Needle "USB19f7:0078"
	}
	True {
		# Multitrack is only for Input enabled
		SectionUseCase."HiFi" {
			Comment "RODECaster Pro II"
			File "/USB-Audio/RODE/RODECaster-Pro-II-USB1-Multitrack-Playback-HiFi.conf"
		}
	}
}
If.usb1_multitrack_capture {
	Condition {
		Type String
		Haystack "${CardComponents}"
		Needle "USB19f7:0030"
	}
	True {
		# Multitrack is only for Output enabled
		SectionUseCase."HiFi" {
			Comment "RODECaster Pro II"
			File "/USB-Audio/RODE/RODECaster-Pro-II-USB1-Multitrack-Capture-HiFi.conf"
		}
	}
}

If.usb2 {
	Condition {
		Type String
		Haystack "${CardComponents}"
		Needle "USB19f7:0026"
	}
	True {
		SectionUseCase."HiFi" {
			Comment "RODECaster Pro II"
			File "/USB-Audio/RODE/RODECaster-Pro-II-USB2-HiFi.conf"
		}
	}
}
