Include.pcm_split.File "/USB-Audio/RODE/RODECaster-Pro-II-USB1-Multitrack-Playback-Channels.conf"

SectionDevice."Speaker" {
	Comment "System"

	Value {
		PlaybackPriority 400
	}
	Macro.pcm_split.SplitPCMDevice {
		Name "rodecaster_pro_ii_stereo_out"
		Direction Playback
		Device 1
		HWChannels 10
		Channels 2
		Channel0 0
		Channel1 1
		ChannelPos0 FL
		ChannelPos1 FR
	}
}

SectionDevice."Line1" {
	Comment "Game"

	Value {
		PlaybackPriority 400
	}
	Macro.pcm_split.SplitPCMDevice {
		Name "rodecaster_pro_ii_stereo_out"
		Direction Playback
		Device 1
		HWChannels 10
		Channels 2
		Channel0 2
		Channel1 3
		ChannelPos0 FL
		ChannelPos1 FR
	}
}

SectionDevice."Line2" {
	Comment "Music"

	Value {
		PlaybackPriority 400
	}
	Macro.pcm_split.SplitPCMDevice {
		Name "rodecaster_pro_ii_stereo_out"
		Direction Playback
		Device 1
		HWChannels 10
		Channels 2
		Channel0 4
		Channel1 5
		ChannelPos0 FL
		ChannelPos1 FR
	}
}

SectionDevice."Line3" {
	Comment "Virtual A"

	Value {
		PlaybackPriority 400
	}
	Macro.pcm_split.SplitPCMDevice {
		Name "rodecaster_pro_ii_stereo_out"
		Direction Playback
		Device 1
		HWChannels 10
		Channels 2
		Channel0 6
		Channel1 7
		ChannelPos0 FL
		ChannelPos1 FR
	}
}


SectionDevice."Line4" {
	Comment "Virtual B"

	Value {
		PlaybackPriority 400
	}
	Macro.pcm_split.SplitPCMDevice {
		Name "rodecaster_pro_ii_stereo_out"
		Direction Playback
		Device 1
		HWChannels 10
		Channels 2
		Channel0 8
		Channel1 9
		ChannelPos0 FL
		ChannelPos1 FR
	}
}

SectionDevice."Mic" {
	Comment "Microphone"

	Value {
		CapturePCM "hw:${CardId},0"
	}
}

SectionDevice."Line5" {
	Comment "Main"

	Value {
		CapturePCM "hw:${CardId},1"
	}
}
