Include.pcm_split.File "/USB-Audio/RODE/RODECaster-Pro-II-USB1-Multitrack-Capture-Channels.conf"

SectionDevice."Line1" {
	Comment "Chat"

	Value {
		PlaybackPCM "hw:${CardId},0"
	}
}

SectionDevice."Speaker" {
	Comment "System"

	Value {
		PlaybackPCM "hw:${CardId},1"
	}
}

SectionDevice."Mic" {
	Comment "Microphone"

	Value {
		CapturePCM "hw:${CardId},0"
	}
}

SectionDevice."Line2" {
	Comment "Main"

	Value {
		PlaybackPriority 400
	}
	Macro.pcm_split.SplitPCMDevice {
		Name "rodecaster_pro_ii_stereo_in"
		Direction Capture
		Device 1
		HWChannels 16
		Channels 2
		Channel0 0
		Channel1 1
		ChannelPos0 FL
		ChannelPos1 FR
	}
}

SectionDevice."Line3" {
	Comment "Combo 1"

	Value {
		PlaybackPriority 400
	}
	Macro.pcm_split.SplitPCMDevice {
		Name "rodecaster_pro_ii_stereo_in"
		Direction Capture
		Device 1
		HWChannels 16
		Channels 1
		Channel0 2
		ChannelPos0 MONO
	}
}

SectionDevice."Line4" {
	Comment "Combo 2"

	Value {
		PlaybackPriority 400
	}
	Macro.pcm_split.SplitPCMDevice {
		Name "rodecaster_pro_ii_stereo_in"
		Direction Capture
		Device 1
		HWChannels 16
		Channels 1
		Channel0 3
		ChannelPos0 MONO
	}
}

SectionDevice."Line5" {
	Comment "Combo 3"

	Value {
		PlaybackPriority 400
	}
	Macro.pcm_split.SplitPCMDevice {
		Name "rodecaster_pro_ii_stereo_in"
		Direction Capture
		Device 1
		HWChannels 16
		Channels 1
		Channel0 4
		ChannelPos0 MONO
	}
}

SectionDevice."Line6" {
	Comment "Combo 4"

	Value {
		PlaybackPriority 400
	}
	Macro.pcm_split.SplitPCMDevice {
		Name "rodecaster_pro_ii_stereo_in"
		Direction Capture
		Device 1
		HWChannels 16
		Channels 1
		Channel0 5
		ChannelPos0 MONO
	}
}

SectionDevice."Line7" {
	Comment "Bluetooth"

	Value {
		PlaybackPriority 400
	}
	Macro.pcm_split.SplitPCMDevice {
		Name "rodecaster_pro_ii_stereo_in"
		Direction Capture
		Device 1
		HWChannels 16
		Channels 2
		Channel0 6
		Channel1 7
		ChannelPos0 FL
		ChannelPos1 FR
	}
}

SectionDevice."Line8" {
	Comment "SMART Pads"

	Value {
		PlaybackPriority 400
	}
	Macro.pcm_split.SplitPCMDevice {
		Name "rodecaster_pro_ii_stereo_in"
		Direction Capture
		Device 1
		HWChannels 16
		Channels 2
		Channel0 8
		Channel1 9
		ChannelPos0 FL
		ChannelPos1 FR
	}
}

SectionDevice."Line9" {
	Comment "System"

	Value {
		PlaybackPriority 400
	}
	Macro.pcm_split.SplitPCMDevice {
		Name "rodecaster_pro_ii_stereo_in"
		Direction Capture
		Device 1
		HWChannels 16
		Channels 2
		Channel0 10
		Channel1 11
		ChannelPos0 FL
		ChannelPos1 FR
	}
}

SectionDevice."Line10" {
	Comment "Chat"

	Value {
		PlaybackPriority 400
	}
	Macro.pcm_split.SplitPCMDevice {
		Name "rodecaster_pro_ii_stereo_in"
		Direction Capture
		Device 1
		HWChannels 16
		Channels 2
		Channel0 12
		Channel1 13
		ChannelPos0 FL
		ChannelPos1 FR
	}
}

SectionDevice."Line11" {
	Comment "USB 2"

	Value {
		PlaybackPriority 400
	}
	Macro.pcm_split.SplitPCMDevice {
		Name "rodecaster_pro_ii_stereo_in"
		Direction Capture
		Device 1
		HWChannels 16
		Channels 2
		Channel0 14
		Channel1 15
		ChannelPos0 FL
		ChannelPos1 FR
	}
}
