#
# Macro HDMI
#
# Arguments:
#
#   Number        HDMI number
#   Device        PCM device number
#   Priority      UCM device priority
#   HdmiPcm       (optional) a non-empty string to use an IEC958 PCM
#

DefineMacro.HDMI {
	If.1 {
		Condition {
			Type RegexMatch
			Regex "(^$|0)"
			String "${var:-__Device}"
		}
		True.Define.__Suffix ""
		False.Define.__Suffix ",pcm=${var:__Device}"
	}
	If.2 {
		Condition {
			Type String
			Empty "${var:-__HdmiPcm}"
		}
		True.Define.__Pcm "hw:${CardId},${var:__Device}"
		False.Define.__Pcm "hdmi${var:__Number}:${CardId}"
		False.LibraryConfig.generic.Config.pcm."hdmi${var:__Number}" {
			@args [ CARD AES0 AES1 AES2 AES3 ]
			@args.CARD.type string
			@args.AES0 { type integer default 0x04 }
			@args.AES1 { type integer default 0x82 }
			@args.AES2 { type integer default 0x00 }
			@args.AES3 { type integer default 0x02 }
			type hooks
			slave.pcm {
				type hw
				card $CARD
				device "${evali:$__Device}"
			}
			hooks.0 {
				type ctl_elems
				hook_args [
				{
					name "IEC958 Playback Default"
					index "${evali:($__Number-1)}"
					lock true
					preserve true
					value [ $AES0 $AES1 $AES2 $AES3 ]
				}
				{
					name "IEC958 Playback Switch"
					index "${evali:($__Number-1)}"
					value true
				}
				]
			}
			hint.device "${evali:$__Device}"
		}
	}
	If.3 {
		Condition {
			Type ControlExists
			Control "iface=CARD,name='HDMI/DP${var:__Suffix} Jack'"
		}
		True.SectionDevice."HDMI${var:__Number}" {
			Comment "HDMI / DisplayPort ${var:__Number} Output"

			EnableSequence [
				cset "name='IEC958 Playback Switch',index=${eval:($__Number-1)} on"
			]

			DisableSequence [
				cset "name='IEC958 Playback Switch',index=${eval:($__Number-1)} off"
			]

			Value {
				PlaybackPriority "${var:__Priority}"
				PlaybackPCM "${var:__Pcm}"
				JackControl "HDMI/DP${var:__Suffix} Jack"
			}
		}
	}
}
