Syntax 4

SectionUseCase."HiFi" {
	File "/MediaTek/mt8366-evk/HiFi.conf"
	Comment "Play high quality music"
}

BootSequence [
	cset "name='ADDA_DL_CH1 DL0_CH1' on"
	cset "name='ADDA_DL_CH2 DL0_CH2' on"
	cset "name='UL0_CH1 ADDA_UL_CH1' on"
	cset "name='UL0_CH2 ADDA_UL_CH2' on"
	cset "name='UL2_CH1 AP_DMIC_UL_CH1' on"
	cset "name='UL2_CH2 AP_DMIC_UL_CH2' on"
	cset "name='PCM_0_PB_CH1 DL2_CH1' on"
	cset "name='PCM_0_PB_CH2 DL2_CH2' on"
	cset "name='UL1_CH1 PCM_0_CAP_CH1' on"
	cset "name='UL1_CH2 PCM_0_CAP_CH2' on"
	cset "name='I2SOUT5_CH1 DL_24CH_CH1' on"
	cset "name='I2SOUT5_CH2 DL_24CH_CH2' on"
	cset "name='I2SOUT5_CH3 DL_24CH_CH3' on"
	cset "name='I2SOUT5_CH4 DL_24CH_CH4' on"
	cset "name='I2SOUT5_CH5 DL_24CH_CH5' on"
	cset "name='I2SOUT5_CH6 DL_24CH_CH6' on"
	cset "name='I2SOUT5_CH7 DL_24CH_CH7' on"
	cset "name='I2SOUT5_CH8 DL_24CH_CH8' on"
	cset "name='I2SOUT5_CH_NUM' 8CH"
	cset "name='UL1_CH1 I2SIN5_CH1' on"
	cset "name='UL1_CH2 I2SIN5_CH2' on"
	cset "name='I2S_OUT5_Mux' Dummy_Widget"
	cset "name='I2S_IN5_Mux' Dummy_Widget"
	cset "name='I2SOUT6_CH1 DL3_CH1' on"
	cset "name='I2SOUT6_CH2 DL3_CH2' on"
	cset "name='UL3_CH1 I2SIN6_CH1' on"
	cset "name='UL3_CH2 I2SIN6_CH2' on"
	cset "name='I2S_OUT6_Mux' Dummy_Widget"
	cset "name='I2S_IN6_Mux' Dummy_Widget"
	cset "name='I2SIN6_CLK_SOURCE' APLL"
	cset "name='I2SIN6_RELATCH_DOMAIN' APLL"
	cset "name='Mic Type Mux' ACC"
]
