Syntax 4

Define.DMI_info "${sys:devices/virtual/dmi/id/board_vendor}-${sys:devices/virtual/dmi/id/product_family}-${sys:devices/virtual/dmi/id/board_name}"

# 4x WSA Speakers | 4x Microphones | 3x DP/HDMI
If.LENOVOSlim7x {
	Condition {
		Type RegexMatch
		String "${var:DMI_info}"
		Regex "LENOVO.*(Yoga Slim 7).*"
	}
	True.Include.7x.File "/Qualcomm/glymur/LENOVO-Slim-7x.conf"
}
