# Use case configuration for Qualcomm Shikra CQM EVK.
# Codec: WSA885x I2S speaker, VA DMIC capture
# Speaker: hw:0,2   DMIC: hw:0,3

SectionVerb {
	EnableSequence [
		cset "name='Rx Slot Mask' 3"
		cset "name='Speaker Volume' 72"
		cset "name='Usage Mode' 3"
	]

	DisableSequence [
		cset "name='Speaker Volume' 0"
	]

	Value {
		TQ "HiFi"
	}
}

SectionDevice."Speaker" {
	Comment "Speaker playback"

	EnableSequence [
		cset "name='Rx Slot Mask' 3"
		cset "name='Speaker Volume' 72"
		cset "name='Usage Mode' 3"
	]

	DisableSequence [
		cset "name='Speaker Volume' 0"
	]

	Value {
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId},2"
		PlaybackChannels 2
	}
}

SectionDevice."Mic" {
	Comment "Internal Digital Microphone Capture"

	Include.vadm0e.File "/codecs/qcom-lpass/va-macro/DMIC0EnableSeq.conf"
	Include.vadm0d.File "/codecs/qcom-lpass/va-macro/DMIC0DisableSeq.conf"
	Include.vadm1e.File "/codecs/qcom-lpass/va-macro/DMIC1EnableSeq.conf"
	Include.vadm1d.File "/codecs/qcom-lpass/va-macro/DMIC1DisableSeq.conf"

	Value {
		CapturePriority 100
		CapturePCM "hw:${CardId},3"
		CaptureChannels 1
	}
}
