# Use case Configuration for sof-hda-dsp

SectionVerb {
	EnableSequence [
		disdevall ""
	]

	Value.TQ "HiFi"
	Value.EldChannels "1"
}

If.analog {
	Condition {
		Type ControlExists
		Control "name='Master Playback Switch'"
	}
	True {
		If.acp {
			Condition {
				Type String
				String1 "${var:MicType}"
				String2 "acp"
			}
			False.Include.analog.File "/HDA/HiFi-analog.conf"
			True.Include {
				acp.File "/HDA/HiFi-acp.conf"
				analog.File "/HDA/HiFi-analog.conf"
			}
		}
	}
}

If.hdmi {
	Condition { Type String Empty "" }
	True.Include.hdmi.File "/HDA/Hdmi.conf"
}
