# HDA Speaker configuration

SectionDevice."Speaker" {
	Comment "Speaker"

	If.seq {
		Condition {
			Type ControlExists
			Control "name='Bass Speaker Playback Switch'"
		}
		True {
			EnableSequence [
				cset "name='Speaker Playback Switch' on"
				cset "name='Bass Speaker Playback Switch' on"
			]

			DisableSequence [
				cset "name='Speaker Playback Switch' off"
				cset "name='Bass Speaker Playback Switch' off"
			]
		}
		False {
			EnableSequence [
				cset "name='${var:spkvol} Playback Switch' on"
			]

			DisableSequence [
				cset "name='${var:spkvol} Playback Switch' off"
			]
		}
	}

	Value {
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId}"
		PlaybackMixerElem "${var:spkvol}"
		PlaybackVolume "${var:spkvol} Playback Volume"
		PlaybackSwitch "${var:spkvol} Playback Switch"
	}

	If.master {
		Condition {
			Type String
			String1 "${var:spkvol}"
			String2 "Master"
		}
		False.Value.PlaybackMasterElem "Master"
	}
}
