# HDA Speaker configuration

Define.SpkDevice "Speaker"

If.spk4ch {
	Condition {
		Type String
		Empty "${var:Speaker4chBass}"
	}
	False.Define.SpkDevice "Speaker1"
}

SectionDevice."${var:SpkDevice}" {
	Comment "Speaker"

	If.seq {
		Condition {
			Type String
			Empty "${var:Speaker4chBass}"
		}
		False {
			EnableSequence [
				cset "name='Speaker 4ch SyncSw Playback Switch' on"
				cset "name='Bass Speaker Playback Switch' on"
			]

			DisableSequence [
				cset "name='Bass Speaker Playback Switch' off"
				cset "name='Speaker 4ch SyncSw Playback Switch' off"
			]

			If.sync_vol {
				Condition {
					Type String
					Empty "${var:SpeakerSyncVol}"
				}
				False {
					EnableSequence [
						cset "name='Speaker 4ch SyncVol Playback Switch' on"
					]

					DisableSequence [
						cset "name='Speaker 4ch SyncVol Playback Switch' off"
					]
				}
			}
		}
	}

	Value {
		PlaybackPriority 110
		PlaybackPCM "hw:${CardId}"
		PlaybackMixer "default:${CardId}"
		PlaybackMixerElem "${var:spkvol}"
		PlaybackVolume "${var:spkvol} Playback Volume"
		PlaybackSwitch "${var:spkvol} Playback Switch"
	}

	If.master {
		Condition {
			Type String
			String1 "${var:spkvol}"
			String2 "Master"
		}
		False {
			EnableSequence [
				cset "name='${var:spkvol} Playback Switch' on"
			]

			DisableSequence [
				cset "name='${var:spkvol} Playback Switch' off"
			]

			Value.PlaybackMasterElem "Master"
		}
	}
}

If.spk4ch {
	Condition {
		Type String
		Empty "${var:Speaker4chBass}"
	}
	False.SectionDevice."Speaker2" {
		Comment "Speaker (4 channels)"

		ConflictingDevice [
			"Speaker1"
		]

		EnableSequence [
			cset "name='Speaker 4ch Playback Switch' on"
			cset "name='Speaker 4ch SyncSw Playback Switch' off"
		]

		DisableSequence [
			cset "name='Speaker 4ch Playback Switch' off"
			cset "name='Speaker 4ch SyncSw Playback Switch' off"
		]

		If.sync_vol {
			Condition {
				Type String
				Empty "${var:SpeakerSyncVol}"
			}
			False {
				EnableSequence [
					cset "name='Speaker 4ch SyncVol Playback Switch' off"
				]

				DisableSequence [
					cset "name='Speaker 4ch SyncVol Playback Switch' off"
				]
			}
		}

		Value {
			PlaybackPriority 100
			PlaybackPCM "hw:${CardId}"
			PlaybackChannels 4
			PlaybackMixer "default:${CardId}"
			PlaybackMasterElem "Master"
			PlaybackMixerElem "Speaker 4ch"
			PlaybackVolume "Speaker 4ch Playback Volume"
			PlaybackSwitch "Speaker 4ch Playback Switch"
		}
	}
}
