Comment "M-Audio M-Track Solo"

SectionUseCase."HiFi" {
	Comment "Default"
	File "/USB-Audio/M-Audio/M-Track-Solo-HiFi.conf"
}

Include.dhw.File "/common/directm.conf"

Macro.0.DirectUseCase { Id="Direct" PlaybackChannels=2 CaptureChannels=2 }
