# cs42l43+cs35l56 specific control settings
#
# Arguments:
#   Amp - amplifier number 1-8
#
DefineMacro.cs35l56spkInit.If.0 {
	Condition {
		Type ControlExists
		Control "name='AMP${var:__Amp} Speaker Switch'"
	}
	True {
		LibraryConfig.remap.Config.ctl.default.map {
			"name='cs42l43 Speaker Playback Switch'" {
				"name='AMP${var:__Amp} Speaker Switch'".vindex.0 0
			}
		}
		FixedBootSequence [
			cset "name='AMP${var:__Amp} Speaker Switch' 0"
		]
		Macro [{ SetLED { LED="speaker" Action="attach" CtlId="AMP${var:__Amp} Speaker Switch" } }]
	}
}

LibraryConfig.remap.Config {
	ctl.default.map {
		"name='cs42l43 Speaker Playback Switch'" {
			"name='cs42l43 Speaker Digital Switch'".vindex.0 [ 0 1 ]
		}
	}
}

Macro [
	{ SetLED { LED="speaker" Action="attach" CtlId="cs42l43 Speaker Digital Switch" } }
	{ cs35l56spkInit { Amp 1 } }
	{ cs35l56spkInit { Amp 2 } }
	{ cs35l56spkInit { Amp 3 } }
	{ cs35l56spkInit { Amp 4 } }
	{ cs35l56spkInit { Amp 5 } }
	{ cs35l56spkInit { Amp 6 } }
	{ cs35l56spkInit { Amp 7 } }
	{ cs35l56spkInit { Amp 8 } }
]
